site_title: "Beri Ink"
site_description: "Fine line tattoo artistry and temporary tattoos"
contact_email: "hello@beri-ink.com"
instagram_url: "https://instagram.com/beri.ink"
etsy_url: "https://www.etsy.com/shop/BeriInk"

