site_title: "Beri Ink"
site_description: "Fine line tattoo artist specializing in delicate, minimalist designs. Vegan and eco-friendly tattooing practices."
contact_email: "beri.tattoo@gmail.com"
instagram_url: "https://www.instagram.com/beri.ink"
facebook_url: ""
tiktok_url: ""
youtube_url: ""
etsy_url: "https://www.etsy.com/shop/BeriInk"
footer_copyright: "© 2025 Beri Ink Tattoo. All rights reserved."
mailing_list_text: "Join our mailing list for new tattoo designs and flash sales."

