backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Temporary Tattoo Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Product Image", name: "image", widget: "image"}
      - {label: "Etsy Link", name: "etsy_link", widget: "string", default: "https://www.etsy.com/shop/BeriInk"}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}

  - name: "gallery"
    label: "Gallery Photos"
    folder: "_gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Photo Title", name: "title", widget: "string"}
      - {label: "Gallery Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 1}

  - name: "artist"
    label: "Artist Photos"
    folder: "_artist"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Photo Title", name: "title", widget: "string"}
      - {label: "Artist Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Order", name: "order", widget: "number", default: 1}

  - name: "settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "general"
        file: "_data/settings.yml"
        fields:
          - {label: "Site Title", name: "site_title", widget: "string", default: "Beri Ink"}
          - {label: "Site Description", name: "site_description", widget: "text"}
          - {label: "Contact Email", name: "contact_email", widget: "string"}
          - {label: "Instagram URL", name: "instagram_url", widget: "string"}
          - {label: "Etsy Shop URL", name: "etsy_url", widget: "string", default: "https://www.etsy.com/shop/BeriInk"}

