backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Temporary Tattoo Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Product Image", name: "image", widget: "image"}
      - {label: "Etsy Link", name: "etsy_link", widget: "string", default: "https://www.etsy.com/shop/BeriInk"}

  - name: "pages"
    label: "Page Content"
    files:
      - label: "Appointment Page"
        name: "appointment"
        file: "_data/appointment-page.yml"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Hero Title", name: "hero_title", widget: "string"}
          - {label: "Consultation Info", name: "consultation_info", widget: "markdown"}
          - {label: "Pricing Info", name: "pricing_info", widget: "markdown"}
